<b><h3>Section A: Data Structures & Control Structures</h3></b>
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
3.	Create a set of integers with some duplicate values. Print the set and explain the output.
4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
6.	Given a 'marks' variable, print the grade:
    - 90 and above: 'A'
    - 75–89: 'B'
    - 50–74: 'C'
    - Below 50: 'Fail'
7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


In [19]:
# 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

lst = [1,2,3,4,5]
print(lst) # Output: [1, 2, 3, 4, 5]

# Append 6 to the list
lst.append(6)
print("Append:", lst)  # Output: [1, 2, 3, 4, 5, 6]

# Extend the list with multiple elements
lst2 = [7, 8, 9,3,2,6,8,5,2,5,3,1,6,3,7,4]
lst.extend(lst2)
print("Extend:", lst)  # Output: [1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 6, 8, 5, 2, 5, 3, 1, 6, 3, 7, 4]

# Insert an element at a specific position
lst.insert(0, 5)  # Insert 5 at index 0
print("Insert:", lst)  # Output: [5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 6, 8, 5, 2, 5, 3, 1, 6, 3, 7, 4]

# Remove an element by value
lst.remove(5)  # Remove the first occurrence of 5
print("Remove:", lst)  # Output: [1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 6, 8, 5, 2, 5, 3, 1, 6, 3, 7, 4]

# pop an element by index
popped_element = lst.pop(0)  # Remove element at index 0
print("Popped Element:", popped_element)  # Output: 1
print("List after pop:", lst)  # Output: [2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 6, 8, 5, 2, 5, 3, 1, 6, 3, 7, 4]

# Index of an element
index_of_5 = lst.index(5)
print("Index of 5:", index_of_5)  # Output: 3

# Count occurrences of an element
count_of_3 = lst.count(3)
print("Count of 3:", count_of_3)  # Output: 4

# Sort the list
lst.sort()
print("Sorted List:", lst)  # Output: [1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 9]

# Reverse the list
lst.reverse()
print("Reversed List:", lst)  # Output: [9, 8, 8, 7, 7, 6, 6, 6, 5, 5, 5, 4, 4, 3, 3, 3, 3, 2, 2, 2, 1]

# Clear the list
lst.clear()
print("Cleared List:", lst)  # Output: []

[1, 2, 3, 4, 5]
Append: [1, 2, 3, 4, 5, 6]
Extend: [1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 6, 8, 5, 2, 5, 3, 1, 6, 3, 7, 4]
Insert: [5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 6, 8, 5, 2, 5, 3, 1, 6, 3, 7, 4]
Remove: [1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 6, 8, 5, 2, 5, 3, 1, 6, 3, 7, 4]
Popped Element: 1
List after pop: [2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 6, 8, 5, 2, 5, 3, 1, 6, 3, 7, 4]
Index of 5: 3
Count of 3: 4
Sorted List: [1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 9]
Reversed List: [9, 8, 8, 7, 7, 6, 6, 6, 5, 5, 5, 4, 4, 3, 3, 3, 3, 2, 2, 2, 1]
Cleared List: []


In [20]:
# 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

students = ("Dinesh", "Raj", "Shyam")

# students[1] = "Ravi"  # This will raise a TypeError
print(students)
# Tuples are immutable, meaning once they are created, their elements cannot be changed or modified

('Dinesh', 'Raj', 'Shyam')


In [21]:
# 3. Create a set of integers with some duplicate values. Print the set and explain the output

numbers = {1, 2, 3, 4, 5, 5, 4, 3, 2, 1}
print(numbers) # Sets automatically remove duplicate values, so the output will be: {1, 2, 3, 4, 5}

{1, 2, 3, 4, 5}


In [22]:
# 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

student = {
    'name': 'Dinesh',
    'age': 20,
    'city': 'Hyderabad'
}

# Update age
student['age'] = 21

# Add email
student['email'] = 'dinesh@example.com'

print(student)

{'name': 'Dinesh', 'age': 21, 'city': 'Hyderabad', 'email': 'dinesh@example.com'}


In [23]:
# 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

age = 21
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")


Eligible to vote


In [24]:
# 6.	Given a 'marks' variable, print the grade:
    # - 90 and above: 'A'
    # - 75–89: 'B'
    # - 50–74: 'C'
    # - Below 50: 'Fail'

marks = 85
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B


In [25]:
# 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

num = 34

if num > 0:
    print("Positive")
    if num % 2 == 0:
        print("Even")
else:
    if num == 0:
        print("Zero")
    else:
        print("Negative")

Positive
Even


<b><h3>Section B: Numpys</h3></b>

8.	Create:
    - A scalar using np.array(5).
    - A 1D array with values 1 to 5.
    - A 2D array (2x3) with values from 10 to 60 in steps of 10.
9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


In [26]:
# 8. Create:
    # - A scalar using np.array(5).
    # - A 1D array with values 1 to 5.
    # - A 2D array (2x3) with values from 10 to 60 in steps of 10.

import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:", scalar) # Output: 5

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d) # Output: [1 2 3 4 5]

# 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:\n", array_2d)  # Output:
                                # [[10 20 30]
                                #  [40 50 60]]

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


<b><h3>Section C: Exploring Pandas</h3></b>

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
    - Use .info(), .describe()
    - Select 'Name' and 'City' columns
    - Drop 'City' column
    - Fill any missing values in 'Salary' column with the mean
    - Remove any duplicate rows


In [27]:
# 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# - Use .info(), .describe()
# - Select 'Name' and 'City' columns
# - Drop 'City' column
# - Fill any missing values in 'Salary' column with the mean
# - Remove any duplicate rows

import pandas as pd
data = {
    'Name': ['Amit', 'Suresh', 'Ravi', 'Anita', 'Priya', 'Vikram', 'Neha', 'Karan', 'Amit', 'Suresh'],
    'Age': [25, 30, 22, 28, 24, 32, 27, 29, 25, 30],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune', 'Ahmedabad', 'Delhi', 'Mumbai'],
    'Salary': [50000, 60000, None, 55000, 52000, None, 58000, 62000, 50000, 60000]
}

df = pd.DataFrame(data)

print("DataFrame Info:")
print(df.info())
print("\nDataFrame Description:")
print(df.describe())

print("\nSelect 'Name' and 'City' columns:")
print(df[['Name', 'City']])

df_dropped = df.drop(columns=['City'])
print("\nDataFrame after dropping 'City' column:")
print(df_dropped)

df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print("\nDataFrame after filling missing 'Salary' values with mean:")
print(df)

df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicate rows:")
print(df_no_duplicates)

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame Description:
             Age        Salary
count  10.000000      8.000000
mean   27.200000  55875.000000
std     3.155243   4793.969426
min    22.000000  50000.000000
25%    25.000000  51500.000000
50%    27.500000  56500.000000
75%    29.750000  60000.000000
max    32.000000  62000.000000

Select 'Name' and 'City' columns:
     Name       City
0    Amit      Delhi
1  Suresh     Mumbai
2    Ravi  Bangalore
3   Anita    Chennai
4   Priya    Kolkata
5  Vikram  Hyderabad
6    Neha       Pune
7   Karan  Ahmedabad
8    Amit      Delhi
9  Suresh     Mumbai

DataFrame after dro

C:\Users\Dinesh\AppData\Local\Temp\ipykernel_15572\1590541290.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
